# version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:      
      - ./config/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/CshApi.conf:/etc/nginx/conf.d/CshApi.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/var/www/frontend
      - ./laravel:/var/www/laravel
      - ./net7.0:/var/www/net7.0
    ports:
      - "80:80"
    depends_on:
      - csh
      - laravel
      - frontend
    networks:
      - app-network

  laravel:
    container_name: laravel
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel/:/var/www/laravel
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - app-network

  csh:
    container_name: csh
    build:
      context: ./net7.0
      dockerfile: Dockerfile
    volumes:
      - ./net7.0/:/var/www/net7.0
    ports:
      - "9001:80"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_MULTIPLE_DATABASES: postgres,laravel,laravelTest
    ports:
      - "35000:5432"
    networks:
      - app-network

  postgres_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
