version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:      
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./laravel:/var/www/public
    ports:
      - "80:80"
    depends_on:
      - laravel
    networks:
      - app-network

  laravel:
    container_name: laravel
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel/:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "35000:5432"
    networks:
      - app-network

  postgres_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
